输入 v (yu) 时显示为 ü
ayaka14732/rime-putonghua pull request #2
Opened 2020-09-14 16:35 UTC by eatradish

例如输入 lv 时输入法显示为 lü

2020-09-14 16:44 UTC, eatradish commented
似乎無用，先不要合併。

2020-09-14 16:58 UTC, eatradish commented
好吧，剛剛我一直想輸入 v 輸入成 u，難怪沒效果。現在有效果了。

![image](https://user-images.githubusercontent.com/19554922/93115537-90c99200-f6ee-11ea-9e8e-99592e64832b.png)

2020-09-15 08:02 UTC, ayaka14732 requested changes
我想了想感觉不太对，后面两行是无效的。应该只加入一行：

```
    - xform (?<!\b)v ü
```

P.S.: 不直接用 `xform v ü` 是因为《汉语拼音方案》也规定了 v 作声母。

2020-09-15 12:06 UTC, eatradish commented
> 我想了想感觉不太对，后面两行是无效的。应该只加入一行：
> 
> ```
>     - xform (?<!\b)v ü
> ```
> 
> P.S.: 不直接用 `xform v ü` 是因为《汉语拼音方案》也规定了 v 作声母。

後兩行是因爲漢語拼音中 ü 的作用域吧。

2020-09-15 12:44 UTC, ayaka14732 commented
不是的，这个问题应该是将 v 改为 ü，但后两行是：

```
    - xform/([nl])ue/$1üe/
    - xform/([jqxy])v/$1u/
```

分别是将 u 改为 ü，以及 v 改为 u，跟本问题无关，看起来像是用于容错，但也没必要加入这两条容错。

2020-09-15 14:18 UTC, eatradish commented
> 不是的，这个问题应该是将 v 改为 ü，但后两行是：
> 
> ```
>     - xform/([nl])ue/$1üe/
>     - xform/([jqxy])v/$1u/
> ```
> 
> 分别是将 u 改为 ü，以及 v 改为 u，跟本问题无关，看起来像是用于容错，但也没必要加入这两条容错。

我覺得有必要，不過我也應該拆分成三個 PR。

2020-09-15 14:22 UTC, eatradish commented
@ayaka14732 cc

2020-09-16 04:00 UTC, ayaka14732 requested changes

2020-09-16 04:00 UTC, ayaka14732 commented on putonghua.schema.yaml
> +    - xform/([nl])v/$1ü/
正则表达式中的分隔符要保持一致，本方案用空格，不要用 `/`。

建议改为 `xform (?<!\b)v ü`，或者保留原写法，作 `xform ([nl])v $1ü`。

2020-09-16 05:23 UTC, ayaka14732 commented
> > 不是的，这个问题应该是将 v 改为 ü，但后两行是：
> > ```
> >     - xform/([nl])ue/$1üe/
> >     - xform/([jqxy])v/$1u/
> > ```
> > 
> > 
> > 分别是将 u 改为 ü，以及 v 改为 u，跟本问题无关，看起来像是用于容错，但也没必要加入这两条容错。
> 
> 我覺得有必要，不過我也應該拆分成三個 PR。

我认为有必要的容错是，例如用户打快了按错键，或者用户因为有口音，平翘舌不分等。而此处将 lue 改为 lüe 等是没有必要的，因为 u 与 v 键距离较远，不可能按错；按 u 与按 v 都是按一个键，没有快慢之分；另外，如果将 lue 容错为 lüe，会影响原来正确的读音，例如「蓼莪」(lù é)。<b>输入法在考虑容错的同时，还有帮助用户纠正普通话发音和掌握拼音的作用。</b>拼音 lüe 不是 lue，这是非常基本的，输入法不应该允许这种错误的写法。

2020-09-16 11:27 UTC, eatradish commented on putonghua.schema.yaml
> +    - xform/([nl])v/$1ü/
Done

2020-09-16 12:08 UTC, ayaka14732 approved these changes

2020-09-16 12:08 UTC, merged